version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weveryone_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Moscow
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "bot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot_network:
    driver: bridge
